### PR TITLE
Compile in bookworm and update alpine to 3.19

### PR DESCRIPTION
**Pull request by andyasp**
[Alpine Release Notes](https://alpinelinux.org/posts/Alpine-3.19.0-released.html)

### CODE REVIEW

**Review by dimitarvdimitrov — APPROVED** [review]

**Comment by andyasp** [comment]
Reran the tests since `golang` uploaded the new images, but now there's a build failure with boringcrypto:
```
#14 [build 5/5] RUN GOOS=linux GOARCH=amd64 make rollout-operator-boringcrypto
#14 0.183 GOEXPERIMENT=boringcrypto GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build -tags netgo ./cmd/rollout-operator
#14 50.25 # github.com/grafana/rollout-operator/cmd/rollout-operator
#14 50.25 /usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
#14 50.25 /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/go-link-4052097540/000023.o: in function `BIO_new_file':
#14 50.25 (.text+0xcb1dc): undefined reference to `fopen64'
#14 50.25 /usr/lib/gcc/x86_64-alpine-linux-musl/13.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/go-link-4052097540/000023.o: in function `BIO_rw_filename':
#14 50.25 (.text+0xcb60d): undefined reference to `fopen64'
#14 50.25 collect2: error: ld returned 1 exit status
```

**Comment by andyasp** [comment]
The build issue has already been reported [upstream](https://gitlab.alpinelinux.org/alpine/aports/-/issues/15573). There's no rush in going to 3.19 for us so I'll keep this PR in draft for the time being.

**Comment by andyasp** [comment]
In the go [issue](https://www.github.com/golang/go/issues/64698) fixing this was declined. Seems that we'll have to go back to compiling in a glibc environment in order to move forward. As a note we've been compiling in alpine since boringcrypto was introduced here in https://github.com/grafana/rollout-operator/pull/71.

**Comment by andyasp** [comment]
Double checked for BoringCrypto in the runtime boringcrypto container (modified to include `go`for the check):
```sh
$ go tool nm /bin/rollout-operator | grep Boring
  16ea60 T crypto/internal/boring/sig.BoringCrypto.abi0
   666a0 t kBoringSSLRSASqrtTwo
   667a0 t kBoringSSLRSASqrtTwoLen
$ go tool nm /bin/rollout-operator | grep StandardCrypto
```

**Review by dimitarvdimitrov — APPROVED** [review]
LGTM, also tried building the image locally and can confirm this correctly builds a boringcrypto image. Thanks for taking care of it!
